# Generated by Django 5.2 on 2025-07-12 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0001_initial'),
    ]

    operations = [
    ]
